package com.postech.auth.handler;
import com.amazonaws.services.lambda.runtime.*; import com.amazonaws.services.lambda.runtime.events.*; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import com.postech.auth.cpf.Documento; import com.postech.auth.repository.AutenticacaoRepository; import com.postech.auth.token.EmissorJwt; import java.sql.SQLException; import java.util.*;
public final class AuthHandler implements RequestHandler<APIGatewayV2HTTPEvent,APIGatewayV2HTTPResponse>{
 private static final ObjectMapper JSON=new ObjectMapper(); private final AutenticacaoRepository repository; private final EmissorJwt emissor;
 public AuthHandler(){this(new AutenticacaoRepository(),new EmissorJwt(System.getenv("JWT_SECRET")));} AuthHandler(AutenticacaoRepository r,EmissorJwt e){repository=r;emissor=e;}
 public APIGatewayV2HTTPResponse handleRequest(APIGatewayV2HTTPEvent e,Context c){String cid=correlation(e);log("request",cid,"POST /api/auth/cpf");try{Map<String,Object>b=JSON.readValue(Optional.ofNullable(e.getBody()).orElse(""),new TypeReference<>(){});Object raw=b.get("cpf");if(!(raw instanceof String cpf)||!cpf.matches("[0-9.\\- ]+"))return response(422,"CPF invalido",cid);Documento d;try{d=new Documento(cpf);}catch(IllegalArgumentException x){return response(422,"CPF invalido",cid);}var found=repository.buscarPorCpf(d.getValor());if(found.isEmpty()||!found.get().elegivel())return response(401,"Nao foi possivel autenticar",cid);var u=found.get();String token=emissor.emitir(u.id().toString(),u.username(),u.roles());return response(200,JSON.writeValueAsString(Map.of("accessToken",token,"tokenType","Bearer","expiresIn",emissor.getValidadeSegundos())),cid);}catch(SQLException x){log("database_error",cid,"database unavailable");return response(503,"Servico temporariamente indisponivel",cid);}catch(Exception x){log("request_error",cid,"invalid request");return response(500,"Erro interno",cid);}}
 private static String correlation(APIGatewayV2HTTPEvent e){String id=null;if(e.getHeaders()!=null)for(var h:e.getHeaders().entrySet())if(h.getKey().equalsIgnoreCase("X-Correlation-ID"))id=h.getValue();if(id==null||id.isBlank())return UUID.randomUUID().toString();String s=id.replaceAll("[^A-Za-z0-9._-]","");return s.isBlank()?UUID.randomUUID().toString():s.substring(0,Math.min(64,s.length()));}
 private static APIGatewayV2HTTPResponse response(int status,String message,String cid){return APIGatewayV2HTTPResponse.builder().withStatusCode(status).withHeaders(Map.of("Content-Type","application/json","X-Correlation-ID",cid)).withBody("{\"message\":\""+message+"\"}").build();} private static void log(String ev,String cid,String detail){System.out.println("{\"event\":\""+ev+"\",\"correlationId\":\""+cid+"\",\"detail\":\""+detail+"\"}");}
}
